apiVersion: v1
kind: Service
metadata:
  name: whisper-asr
  labels:
    app: whisper-asr
    app.kubernetes.io/name: whisper-asr
    app.kubernetes.io/component: transcription
    app.kubernetes.io/part-of: griot-and-grits
spec:
  selector:
    app: whisper-asr
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
